# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2026 Pavel Ivanov <predefine@yandex.ru>

ifdef CONFIG_VIDEO_MTK
obj-y += common.o
obj-$(CONFIG_VIDEO_MTK_DSI) += dsi.o
obj-$(CONFIG_VIDEO_MTK_MUTEX) += mutex.o
obj-$(CONFIG_VIDEO_MTK_MMSYS) += mmsys.o
obj-$(CONFIG_VIDEO_MTK_RDMA) += rdma.o
obj-$(CONFIG_VIDEO_MTK_OVL) += ovl.o
obj-$(CONFIG_VIDEO_MTK_DISPLAY_PWM) += display_pwm.o
endif
