# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_IOMMU) += iommu-uclass.o

obj-$(CONFIG_APPLE_DART) += apple_dart.o
obj-$(CONFIG_SANDBOX) += sandbox_iommu.o
obj-$(CONFIG_QCOM_HYP_SMMU) += qcom-hyp-smmu.o
obj-$(CONFIG_MEDIATEK_IOMMU) += mediatek_m4u.o mediatek_smi_larb.o
