#ifndef __MTK_PWRAP_H_
#define __MTK_PWRAP_H_

enum {
  MTK_PWRAP_REG_INIT_DONE2 = 0x98,
  MTK_PWRAP_REG_WACS2_CMD = 0x9C,
  MTK_PWRAP_REG_WACS2_RDATA = 0xA0,
  MTK_PWRAP_REG_WACS2_VLDCLR = 0xA4,
};

enum {
  PWRAP_FSM_WAIT_FOR_IDLE = 0x0,
  PWRAP_FSM_WAIT_FOR_VALID_CLR = 0x6,
};

#endif /* __MTK_PWRAP_H_ */
